# Generated by Django 5.2.11 on 2026-02-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="С какого дня начинает действовать привычка. Если не указана — с даты создания.",
                null=True,
                verbose_name="Дата начала",
            ),
        ),
    ]
